service: keyme-serlverless

provider:
  name: aws
  region: ap-northeast-2
  stage: prod
  runtime: java17
  timeout: 60

package:
  artifact: build/libs/keyme-serverless-lambda.jar

functions:
  errorLogHandler:
    handler: space.keyme.keymeserverless.log.ErrorLogHandler
    environment:
      FUNCTION_NAME: errorLogHandler
