service: keyme-serlverless

provider:
  name: aws
  region: ap-northeast-2
  stage: prod
  runtime: java17
  timeout: 60

package:
  artifact: build/libs/keyme-serverless-lambda.jar

functions:
  errLogSendToDiscord:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    environment:
      FUNCTION_NAME: errLogSendToDiscord